PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Users ( UserID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, Email VARCHAR(50) NOT NULL, Password VARCHAR(50) NOT NULL, Username VARCHAR(30) );
CREATE TABLE Lists (
ListID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
UserID INTEGER,
ListName VARCHAR(30) NOT NULL,
FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
CREATE TABLE Tasks (
TaskID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
ListID INTEGER,
TaskName VARCHAR(100),
Status BOOLEAN NOT NULL CHECK (Status IN (0, 1)),
FOREIGN KEY (ListID) REFERENCES Lists(ListID)
);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('Users',2);
INSERT INTO sqlite_sequence VALUES('Lists',1);
INSERT INTO sqlite_sequence VALUES('Tasks',2);
COMMIT;
